### PR TITLE
Update to Twemoji v12.1.3

### LINKED ISSUE #48: Update to Twemoji v12
This isn't imminent, but filing for tracking.

- [x] Wait for v12 to bed down a little more first (12.0.1 just released adding missing hair components) 
- [x] Wait for emojibase to update: milesj/emojibase#20

### PR DESCRIPTION
**Pull request by KwanEsq**
@jfkthame

Fixes #48

### CODE REVIEW

**Comment by polarathene** [comment]
Is there anything blocking the merge so that the v12 update can be released? 4 months with no code review?

**Comment by KwanEsq** [comment]
Ping @jfkthame

**Comment by jfkthame** [comment]
I'm going to assume this is OK :) ... I was hoping to build the new version locally and take a look, but it's not working for me; seems to be some issues with versions of node stuff, but I don't really know how to disentangle it and get a working build. So I'll assume you can provide a generated font based on the updated sources.

**Comment by KwanEsq** [comment]
Thanks a lot!
Here's a .zip with the .ttf and .ttx generated by make with 83fd398 checked out:
[build-0.5.0.zip](https://github.com/mozilla/twemoji-colr/files/3791221/build-0.5.0.zip)

**Pull request merged**
