### PR TITLE
Update to Twemoji v11.4.0.

### LINKED ISSUE #34: update to Twemoji v11.0

### PR DESCRIPTION
**Pull request by KwanEsq**
Fixes #34.

Is there anything in particular to do to test this to make sure it's okay?

I replaced the browser/fonts/TwemojiMozilla.ttf in Firefox and rebuilt it, loaded https://emojipedia.org/unicode-11.0/ and saw all the new ones seem to display fine.

### CODE REVIEW

**Comment by KwanEsq** [comment]
I actually meant to link https://emojipedia.org/emoji-11.0/, which tests more of the new ones since it does the combos as well as the standalone ones.

**Comment by timdream** [comment]
Please also update the version in `package.json`.

**Comment by timdream** [comment]
@TheEssemCraft Could you help review the changes?

**Comment by timdream** [comment]
Perhaps also land this on Firefox?

**Comment by KwanEsq** [comment]
> Please also update the version in package.json.

Thanks, done!
>Perhaps also land this on Firefox?

I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1470107, and I'll submit a patch if and when this is merged.

**Comment by haiwx** [comment]
@KwanEsq Could you provide the TwemojiMozilla.ttf (0.4.0) for me, I fail in building it, thanks! 

https://send.firefox.com/

**Comment by roytam1** [comment]
what about updating to v11.2?

**Pull request merged**
