### PR TITLE
Generating screenshots of all glyphs with SlimerJS

### PR DESCRIPTION
**Pull request by timdream**
Addresses #8.

The good thing is it could take a shot of the page content, so we don't need to go through the canvas element (and we don't rely on Nightly). This incidentally workaround the fact that SlimerJS only works with specific version of XULRunner/Firefox, not the latest Nightly.

The bad thing is that it could not generate a PNG of transparent background, since a webpage is not transparent at first place.

To do:
- Allow passing a specific code point and only generate that.

(Edit: Remove description on speed; there was a mistake made on my original commit)

### CODE REVIEW

**Comment by timdream** [comment]
This is the `time` result. Not bad!

    real	1m25.905s
    user	1m19.070s
    sys 	0m6.688s

**Comment by timdream** [comment]
The script here now generates SVG rendering and font rendering. I wonder what kind of operation we want to compare these images? We could do a simple `convert foo bar -compare baz` (not really more useful than the in-browser testing page we got now), and all the way up to build up a customize computer vision tool.

This would take some time to figure out...

**Comment by flying-sheep** [comment]
solutions for the transparency problem:

1. wait for laurentj/slimerjs#154 to be fixed
2. render without antialiasing once to get an alpha channel, then apply the channel to a normally rendered image.

**Comment by timdream** [comment]
Cleaning-up; feel free to pickup published commits.

**Pull request closed without merging**
