### PR TITLE
Update to Twemoji 14.0.1 (Emoji 14.0)

### LINKED ISSUE #64: Update to 14.0.0
[Upstream 14.0.0 relase](https://github.com/twitter/twemoji/releases/tag/v14.0.0) which supports emojis from Unicode 14

### PR DESCRIPTION
**Pull request by win98se**
The changes are done along with @KohGeek.

Will fix #64; Also includes a workaround for twitter/twemoji#537.

Additional notes:
- On Node versions 16 and 17 (should work on all versions >=12 I guess), before running `npm install` (as in “Getting started” part in `README.md`), I have to run `npm install --package-lock-only --ignore-scripts && npx npm-force-resolutions` so that the `make` step (as in “Building the font” part also in `README.md`) will run successfully.
- I have also edited `CONTRIBUTE.md` and `README.md` to reflect recent changes as in previous pulls.

### CODE REVIEW

**Comment by win98se** [comment]
The just released Twemoji 14.0.2 introduces no changes to SVGs.

**Comment by Caspy7** [comment]
Don't mean to be a bother, I'm curious if someone could tell me what are the next steps for this to land. Are there any blockers? Do we need to find a particular owner for the code?

**Comment by win98se** [comment]
> What are the next steps for this to land. Are there any blockers? Do we need to find a particular owner for the code?

Pinging @jfkthame for attention.

**Comment by ZeWaka** [comment]
Would be great if this could be merged and a release cut - just bumping the thread.

**Comment by jfkthame** [comment]
I'm going to go ahead and merge this, but when building it locally I see a couple of additional issues that we should fix for the new version: there's an obsolete family-group ligature that we should remove, and the new twemoji has a glyph that uses the "fill-opacity" attribute instead of "opacity", which we don't currently handle. I'll do followup fixes for these.

**Pull request merged**
