### PR TITLE
Update Twemoji to 2.6

### PR DESCRIPTION
**Pull request by TheEssemCraft**

### CODE REVIEW

**Comment by timdream** [comment]
Can you give some introductions on what this will fix? We don't really want to follow every minor revision, given its labor intensive.

**Comment by TheEssemCraft** [comment]
It just changes a few emojis, nothing special. I guess we could skip this version.

**Comment by timdream** [comment]
Thanks. Once you have good local setup to produce meaningful commit messages, I'll be happy to ask around on the rules of getting you the commit access to this repo.

**Comment by TheEssemCraft** [comment]
Ok, I've set up the development environment on my computer.

**Pull request closed without merging**
