### PR TITLE
Add improvements from mrdrogdrog/master

### PR DESCRIPTION
**Pull request by mrdrogdrog**
I really like this project (despite the fact that it's quite a mess. :sweat_smile: ) so I want to give back some of my personal improvements.

- Rename font file to just "twemoji" to get rid of the space.
  *The white space in the file name is rather annoying*
- Generate "woff2" instead of "ttf".
  *It's 2021. Nobody should use ttf files*
- Reformat "layerize.js"
  *Corrected some white spaces, indentations and added triple equal signs*
- Get rid of twe-svg.zip repacking
  *I altered layerize.js so you don't have to repackage twe-svg.zip anymore*
- Update libs
  *Node lib updates*
- Use python3

Hope you like it!

### CODE REVIEW

**Comment by jfkthame** [comment]
Thanks for your suggestions/contribution! Could I ask you to split this into individual commits for each item, which can be considered/merged separately? Regarding each of the items mentioned:

> Rename font file to just "twemoji" to get rid of the space.

Please make it "TwemojiMozilla.ttf" (i.e. just eliminate the space, but keep the Mozilla suffix because we want to be clear that this is not part of the upstream Twemoji project itself, it's a Mozilla derivative). This will match how it is actually shipped in Firefox (see https://hg.mozilla.org/mozilla-central/file/tip/browser/fonts).

> Generate "woff2" instead of "ttf".

I don't necessarily agree with this. TTF is the canonical font format for an OpenType font with TrueType outlines. WOFF2 is a compression/packaging of this targeted at webfont use, but is not necessarily optimal for all use cases. (E.g. a TTF file can be directly mapped into memory and used, whereas the WOFF2 has to first go through a decompression to a separate memory buffer. So depending on the usage scenario, the runtime RAM footprint of WOFF2 may actually be larger.)

>  Reformat "layerize.js"
>  Get rid of twe-svg.zip repacking
>  Update libs
>  Use python3

These changes sound fine, although I haven't looked at the details yet.

**Comment by stone-zeng** [comment]
> * Generate "woff2" instead of "ttf".
>   _It's 2021. Nobody should use ttf files_

Need to mention that a lot of applications other than web browsers cannot use WOFF2 format, so TTF is still necessary.

**Comment by mrdrogdrog** [comment]
Okay, I changed some things:

- I split the commit into multiple commits
- I renamed the font to "TwemojiMozilla" (like before but without the space)
- I didn't replace the zip file because it doesn't matter right if it's the full zip or the repacked one.
- I reverted the woff2 change. I still think that a woff2 file should be created as well but I get your concerns.

**Comment by mrdrogdrog** [comment]
What do you think @jfkthame ?

**Comment by jfkthame** [comment]
Thanks for the update. One question (as I haven't pulled this and tried a build myself yet):

>     * I renamed the font to "TwemojiMozilla" (like before but without the space)

Does this rename the font itself (internally) so that its family name no longer has a space? What I'd really prefer to see is that the *font family name* remains "Twemoji Mozilla" (with a space), while the *filename* becomes TwemojiMozilla.ttf. Can we get that result?

**Comment by mrdrogdrog** [comment]
Hm as far as I can see no because grunt-webfonts uses the internal name as file name. Well. The name thing isn't that important. I dropped it.

**Review by jfkthame — COMMENTED** [review]
While you're tidying things up, would you mind also fixing the whitespace in Gruntfile.js? It seems to have an ugly mix of tabs and spaces, which can make it look confusing depending on the tab settings in the editor/viewer.

Unless "real" tabs are strictly required for some reason, I'd prefer to just use spaces so that the indentation is stable regardless of editor settings.

Thanks!

**Comment by mrdrogdrog** [comment]
Fixed it

**Comment by jfkthame** [comment]
LGTM - thanks for doing this.

**Comment by mrdrogdrog** [comment]
No problem. I have many more improvements waiting for a PR :smirk: (as soon as they're finished)

**Comment by Ypnose** [comment]
@mrdrogdrog As it was mentioned in previous comments, replacing TTF by WOFF2 will create issues. Even if Fontconfig seems to support WOFF2 thanks to FreeType, it seems it still has [problems](https://wiki.debian.org/Fonts/PackagingPolicy). Some people (including me) directly use Twemoji as a font in terminal emulators or other GUI programs.

**Pull request merged**
